# Docker Compose với ngrok tunnel
services:
  # FastAPI service
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CORS_ORIGINS=*
    volumes:
      - ./data:/app/data # Chỉ mount thư mục data, log sẽ nằm trong đây
      - ./test:/app/test # Mount thư mục test để có thể truy cập test files
    networks:
      - app_network
    mem_limit: 2g # Giới hạn bộ nhớ tối đa 2GB cho container FastAPI

  # Ngrok tunnel
  ngrok:
    image: ngrok/ngrok:latest
    command: http api:8000 --authtoken=${NGROK_AUTHTOKEN} --url=${NGROK_URL}
    ports:
      - "4040:4040"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
