# Docker Compose với ngrok tunnel
version: "3.8"

services:
  # FastAPI service
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=*
    volumes:
      - ./data:/app/data
      - ./test:/app/test
    networks:
      - app_network

  # Ngrok tunnel
  ngrok:
    image: ngrok/ngrok:latest
    command: http api:8000 --authtoken=${NGROK_AUTHTOKEN} --url=${NGROK_URL}
    ports:
      - "4040:4040"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
