# Docker Compose override for development
# Usage: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

services:
  video:
    build:
      target: development
      args:
        - DEV_MODE=true
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      # Mount source code for hot reload in development
      - ./app:/app/app:ro
      - ./utils:/app/utils:ro
      - ./requirements.txt:/app/requirements.txt:ro
    command: >
      uvicorn app.main:app 
      --host 0.0.0.0 
      --port 8000 
      --reload 
      --log-level debug
      --workers 1
    ports:
      - "8000:8000"
      - "8001:8001" # Debug port
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.1"

  # Optional: Redis for caching in development
  redis:
    image: redis:7-alpine
    container_name: cont_redis_dev
    ports:
      - "6379:6379"
    networks:
      - video_network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.1"

  # Optional: MinIO for object storage testing
  minio:
    image: minio/minio:latest
    container_name: cont_minio_dev
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - video_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.2"

volumes:
  minio_data:
    driver: local
